version: '3'

services:
  db:
    image: postgres:16 # Use a specific PostgreSQL version
    restart: always
    environment:
      POSTGRES_DB: mydatabase # Name of the database
      POSTGRES_USER: myuser # Username for the database
      POSTGRES_PASSWORD: mypassword # Password for the database user
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persists database data

volumes:
  db_data: # Define the named volume for data persistencedocker volume inspect db_data
